# Generated by Django 4.2.6 on 2023-10-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(default='images/pill.svg', upload_to='')),
                ('icon_birch', models.ImageField(default='images/pill_birch.svg', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(default='images/doctor.svg', upload_to='')),
                ('icon_pink', models.ImageField(default='images/doctor_pink.svg', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('ntype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
