# Generated by Django 4.2.6 on 2023-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetype',
            name='icon',
            field=models.ImageField(default='images/procedure/pill.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='icon_birch',
            field=models.ImageField(default='images/procedure/pill_birch.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='icon',
            field=models.ImageField(default='images/procedure/doctor.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='icon_pink',
            field=models.ImageField(default='images/procedure/doctor_pink.svg', upload_to=''),
        ),
    ]
